name: CI - Build & Test

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean package -DskipTests=false

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pull Request to Develop
        id: create_pr
        run: |
          # Verifica se a branch já difere da develop
          git fetch origin develop
          if git diff --quiet origin/develop..HEAD; then
            echo "❌ Branch está igual à develop, PR não será criado"
            exit 1
          fi

          # Cria o PR
          gh pr create \
            --base develop \
            --head ${{ github.ref_name }} \
            --title "Auto PR - Merge ${{ github.ref_name }} into develop" \
            --body "Este PR foi criado automaticamente pelo workflow de CI.\n- Branch: ${{ github.ref_name }}\n- Pipeline: ${{ github.workflow }}" \
            --label automated
