name: CD - Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (staging)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/complicheck:staging .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/complicheck:staging

      - name: Deploy to Staging (placeholder)
        run: echo "Deploying to staging environment..."

      - name: Create PR to Main
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: develop
          title: "Auto PR - Merge develop into main"
          body: |
            Este PR foi criado automaticamente pelo workflow de CD.
            - Branch: develop
            - Pipeline: ${{ github.workflow }}
          labels: automated

      - name: Fail if PR not created
        if: steps.create_pr.outputs.pull-request-operation == 'none'
        run: |
          echo "❌ Nenhum PR foi criado — branch develop está igual à main."
          exit 1
