name: CI - Build & Test

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean package -DskipTests=false

      - name: Create Pull Request to Develop
        id: create_pr
        if: success()
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: "Auto PR - Merge ${{ github.ref_name }} into develop"
          body: |
            Este PR foi criado automaticamente pelo workflow de CI.
            - Branch: ${{ github.ref_name }}
            - Pipeline: ${{ github.workflow }}
          labels: automated

      - name: Fail if PR not created
        if: steps.create_pr.outputs.pull-request-operation == 'none'
        run: |
          echo "❌ Nenhum PR foi criado — branch está igual à develop."
          exit 1

